
version: '3'

services:
  # Local LLM server
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G
    restart: unless-stopped

  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Vector database
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    restart: unless-stopped

  # Object storage (S3 compatible)
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    restart: unless-stopped

  # Search engine
  searxng:
    image: searxng/searxng
    ports:
      - "8080:8080"
    volumes:
      - searxng_data:/etc/searxng
    restart: unless-stopped

  # CrewAI application
  crewai:
    build: ./
    depends_on:
      - postgres
      - ollama
      - chroma
      - minio
      - searxng
    environment:
      DB_CONNECTION_STRING: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      VECTOR_DB_HOST: chroma
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      SEARXNG_HOST: searxng
      OLLAMA_HOST: ollama
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
  chroma_data:
  minio_data:
  ollama_models:
  searxng_data:
