# Finance Tasks Configuration
# This file contains task definitions for financial operations
# using the Plaid API for account access, transaction analysis,
# budgeting, and investment tracking

# Plaid API Documentation:
# --------------------------
# These tasks use the Plaid API for accessing financial data.
# Plaid provides secure access to banking data through a unified API.
# Key features include:
#   - Account and balance information
#   - Transaction history and categorization
#   - Identity verification
#   - Investment holdings and transactions
#   - Liabilities information
#
# API Reference: https://plaid.com/docs/
# Authentication: All requests require client_id, secret, and access_token
# Environment: Tasks can run in sandbox, development, or production environments

finance_tasks:
  # Account Management Tasks
  create_link_token:
    name: "Create Plaid Link Token"
    description: "Create a Link token for initializing Plaid Link to securely connect user bank accounts."
    expected_output: "Link token for frontend integration with expiration time."
    required_tools:
      - "create_link_token"
    dependencies: []
    agent: "financial_assistant"
    priority: "high"
    parameters:
      user_id: "user_identifier"
      client_name: "RuTwin Financial Assistant"
      products:
        - "transactions"
        - "auth"
        - "identity"
        - "investments"
      country_codes:
        - "US"

  exchange_public_token:
    name: "Exchange Public Token for Access Token"
    description: "Exchange a public token from Plaid Link for a permanent access token."
    expected_output: "Access token and item ID for future API requests."
    required_tools:
      - "exchange_public_token"
    dependencies:
      - "create_link_token"
    agent: "financial_assistant"
    priority: "high"
    parameters:
      public_token: "public_token_from_link"

  get_account_overview:
    name: "Get Financial Account Overview"
    description: "Retrieve and summarize all financial accounts connected through Plaid."
    expected_output: "Comprehensive overview of all accounts with balances and account types."
    required_tools:
      - "get_accounts"
      - "get_account_balances"
    dependencies:
      - "exchange_public_token"
    agent: "financial_analyst"
    priority: "high"
    parameters:
      include_balances: true

  verify_account_identity:
    name: "Verify Account Identity"
    description: "Verify account ownership by retrieving identity information from financial institutions."
    expected_output: "Verified identity information including names, emails, and addresses."
    required_tools:
      - "get_account_identity"
    dependencies:
      - "get_account_overview"
    agent: "financial_assistant"
    priority: "medium"
    parameters: {}

  # Transaction Analysis Tasks
  analyze_recent_transactions:
    name: "Analyze Recent Transactions"
    description: "Retrieve and analyze recent transactions across all connected accounts."
    expected_output: "Transaction summary with statistics and categorization."
    required_tools:
      - "get_transactions"
      - "categorize_transactions"
    dependencies:
      - "get_account_overview"
    agent: "financial_analyst"
    priority: "high"
    parameters:
      start_date: "30_days_ago"
      end_date: "today"
      count: 500

  search_specific_transactions:
    name: "Search for Specific Transactions"
    description: "Search transaction history for specific merchants, amounts, or categories."
    expected_output: "Filtered list of transactions matching search criteria."
    required_tools:
      - "search_transactions"
    dependencies:
      - "analyze_recent_transactions"
    agent: "financial_assistant"
    priority: "medium"
    parameters:
      query: "search_term"
      min_amount: null
      max_amount: null
      start_date: null
      end_date: null

  enrich_transaction_data:
    name: "Enrich Transaction Data"
    description: "Add additional context to transaction data including merchant information and spending insights."
    expected_output: "Enriched transaction data with merchant details and contextual information."
    required_tools:
      - "enrich_transactions"
    dependencies:
      - "analyze_recent_transactions"
    agent: "data_analyst"
    priority: "medium"
    parameters: {}

  # Budget Planning Tasks
  create_monthly_budget:
    name: "Create Monthly Budget"
    description: "Create a personalized monthly budget based on income and spending patterns."
    expected_output: "Detailed budget with category allocations and total budget amount."
    required_tools:
      - "create_budget"
      - "analyze_spending"
    dependencies:
      - "analyze_recent_transactions"
    agent: "financial_planner"
    priority: "high"
    parameters:
      name: "Monthly Budget"
      period: "monthly"
      start_date: "first_day_of_month"
      group_by: "category"

  analyze_budget_performance:
    name: "Analyze Budget Performance"
    description: "Compare actual spending against budget to identify areas of overspending or savings."
    expected_output: "Budget performance report with category-level analysis and recommendations."
    required_tools:
      - "analyze_budget"
      - "get_transactions"
    dependencies:
      - "create_monthly_budget"
    agent: "financial_analyst"
    priority: "medium"
    parameters: {}

  forecast_cash_flow:
    name: "Forecast Cash Flow"
    description: "Predict future cash flow based on recurring income, expenses, and account balances."
    expected_output: "Cash flow forecast with daily projections and ending balance estimates."
    required_tools:
      - "forecast_cash_flow"
      - "identify_recurring_expenses"
    dependencies:
      - "analyze_recent_transactions"
      - "get_account_balances"
    agent: "financial_planner"
    priority: "high"
    parameters:
      forecast_days: 90
      include_recurring: true

  # Income Analysis Tasks
  verify_income_sources:
    name: "Verify Income Sources"
    description: "Identify and verify income sources from transaction history."
    expected_output: "Verified monthly income with source breakdown and stability assessment."
    required_tools:
      - "verify_income"
    dependencies:
      - "analyze_recent_transactions"
    agent: "financial_analyst"
    priority: "high"
    parameters:
      months: 3

  analyze_income_patterns:
    name: "Analyze Income Patterns"
    description: "Analyze income trends, growth, and payment patterns over time."
    expected_output: "Income pattern analysis with growth trends and payment frequency information."
    required_tools:
      - "analyze_income_patterns"
    dependencies:
      - "verify_income_sources"
    agent: "financial_analyst"
    priority: "medium"
    parameters:
      months: 6

  # Financial Health Tasks
  assess_financial_health:
    name: "Assess Overall Financial Health"
    description: "Evaluate overall financial health based on income, expenses, debt, and savings."
    expected_output: "Financial health score with detailed metrics and improvement recommendations."
    required_tools:
      - "assess_financial_health"
    dependencies:
      - "analyze_recent_transactions"
      - "verify_income_sources"
      - "get_account_balances"
    agent: "financial_planner"
    priority: "high"
    parameters: {}

  analyze_debt_situation:
    name: "Analyze Debt Situation"
    description: "Analyze current debt load and develop optimal repayment strategies."
    expected_output: "Debt analysis with repayment plan options and interest savings calculations."
    required_tools:
      - "analyze_debt"
    dependencies:
      - "assess_financial_health"
    agent: "financial_planner"
    priority: "high"
    parameters: {}

  plan_savings_goal:
    name: "Plan for Savings Goal"
    description: "Create a plan to reach a specific savings goal based on current finances."
    expected_output: "Savings plan with timeline, required contributions, and milestone projections."
    required_tools:
      - "plan_savings_goal"
    dependencies:
      - "assess_financial_health"
    agent: "financial_planner"
    priority: "medium"
    parameters:
      goal_amount: 10000
      current_savings: 0
      monthly_contribution: 500
      interest_rate: 0.01

  # Spending Analysis Tasks
  analyze_spending_patterns:
    name: "Analyze Spending Patterns"
    description: "Analyze spending patterns by category, merchant, or time period."
    expected_output: "Comprehensive spending analysis with trends and distribution breakdown."
    required_tools:
      - "analyze_spending"
    dependencies:
      - "analyze_recent_transactions"
    agent: "financial_analyst"
    priority: "high"
    parameters:
      group_by: "category"
      start_date: "90_days_ago"
      end_date: "today"

  analyze_merchant_spending:
    name: "Analyze Merchant Spending"
    description: "Analyze spending patterns with specific merchants to identify opportunities for savings."
    expected_output: "Merchant spending analysis with frequency and amount trends."
    required_tools:
      - "analyze_merchants"
    dependencies:
      - "analyze_spending_patterns"
    agent: "financial_analyst"
    priority: "medium"
    parameters:
      months: 3

  identify_recurring_expenses:
    name: "Identify Recurring Expenses"
    description: "Identify recurring subscriptions and regular expenses from transaction history."
    expected_output: "List of recurring expenses with amounts, frequency, and next expected dates."
    required_tools:
      - "identify_recurring_expenses"
    dependencies:
      - "analyze_recent_transactions"
    agent: "financial_assistant"
    priority: "high"
    parameters:
      min_occurrences: 2
      amount_tolerance: 1.0
      days: 90

  # Investment Tracking Tasks
  track_investment_holdings:
    name: "Track Investment Holdings"
    description: "Retrieve and analyze current investment holdings across connected accounts."
    expected_output: "Investment portfolio summary with holdings breakdown and allocation analysis."
    required_tools:
      - "get_investment_holdings"
    dependencies:
      - "get_account_overview"
    agent: "investment_advisor"
    priority: "high"
    parameters: {}

  analyze_investment_transactions:
    name: "Analyze Investment Transactions"
    description: "Analyze investment transactions to track performance and activity."
    expected_output: "Investment transaction analysis with buy/sell activity and security breakdown."
    required_tools:
      - "get_investment_transactions"
    dependencies:
      - "track_investment_holdings"
    agent: "investment_advisor"
    priority: "medium"
    parameters:
      start_date: "365_days_ago"
      end_date: "today"

  analyze_portfolio_performance:
    name: "Analyze Portfolio Performance"
    description: "Analyze investment portfolio performance and alignment with risk tolerance."
    expected_output: "Portfolio analysis with risk assessment and rebalancing recommendations."
    required_tools:
      - "analyze_portfolio"
    dependencies:
      - "track_investment_holdings"
    agent: "investment_advisor"
    priority: "high"
    parameters:
      risk_tolerance: "moderate"

  optimize_asset_allocation:
    name: "Optimize Asset Allocation"
    description: "Analyze and optimize asset allocation based on investment goals and risk profile."
    expected_output: "Asset allocation analysis with rebalancing recommendations and target allocations."
    required_tools:
      - "analyze_asset_allocation"
    dependencies:
      - "analyze_portfolio_performance"
    agent: "investment_advisor"
    priority: "medium"
    parameters:
      target_allocation:
        cash: 5
        bond: 30
        stock: 45
        etf: 15
        mutual_fund: 5
